### ISSUE TITLE
Invalid currency configuration does not throw error

### ISSUE THREAD

**Issue by byudaniel** [flexdrive/f1-utils#2]
An invalid currency configuration does not throw an error, but instead throws a reference error when it tries to call `.format` on the non-existent configuration.
https://github.com/flexdrive/f1-utils/blob/de9b58e084696a1e9698a228d8e6bb4fbc4dcb84/src/currency/index.js#L31

**Comment by jason-flexdrive** [comment]
Fixed in v1.1.3
